services:
   mongo-db:
      image: mongo:6.0
      ports:
          - "27017:27017"
      volumes:
          - mongo-data:/data/db
      networks:
          - plantdiary-network

   backend:
      image: srnaagoli/backend:v2
      ports: 
         - "8080:8080"
      depends-on:
         - mongo-db
      networks:
         - plantiary-network

   frontend:
      image: srnaagoli/frontend:v2
      ports:
         - "5173:80"
      depends-on:
         - backend
      networks:
         - plantdiary-network

   volumes:
      mongo-data:

   networks:
      plantdiary-network:

